### ISSUE TITLE
isLoggable() should use Timber's isLoggable()

### ISSUE THREAD

**Issue by drewhamilton** [patrickfav/slf4j-timber#1]
`TimberAndroidLoggerAdapter.isLoggable()` always returns true, stating that Timber will decide if the log will actually be used. This is true, but it means all of the SLF4J string formatting gets done even if Timber ends up deciding it's not loggable.

I think `isLoggable()` should instead be implemented something like the following, to stop any formatting from being done if the log isn't going to be logged:
```java
private boolean isLoggable(int priority) {
    List<Tree> forest = Timber.forest();
    if (forest.isEmpty()) {
        return false;
    } else {
        for (Tree tree : forest) {
            if (tree.isLoggable(name, priority) {
                return true;
            }
        }
        return false;
    }
}
```
I'd be happy to make a PR for this if you agree.

**Comment by patrickfav** [comment]
So basically I agree. Here are some thoughts:

* `isLoggable` is called on every log event, so this having a time complexity of `O(n)` is not super sexy, on the other hand I guess 98% of cases there will be a single tree, so I guess this is fine in practice.
* The default implementation in the `abstract Tree`  always returns true; again I claim that ~98% of users won't change that, making the check unnecessary
* This is, however, the more correct check when thinking about it.

In the end it will be very use cases depended if this change will save or cost cpu/memory; but again I think that is the more correct implementation. So I would very much welcome a PR :)

**Comment by drewhamilton** [comment]
Thanks for the response. I agree the `O(n)` complexity isn't great—I'll double check the message formatting is actually slower than this; if not it would be silly to implement this. At the very least I want it to return false if no trees are planted, though.

Is there any way to make the check configurable? I have no experience with SLF4J at all before this, but it seems like it wouldn't be easy to make this configurable since the adapter seems to be used automagically instead of manually instantiated anywhere.

Anyway, hopefully I'll be able to get a PR up decently soon.

**Comment by patrickfav** [comment]
> Is there any way to make the check configurable?

Unfortunately there is no way to directly configure a logger, since SLF4J will automagically instantiate the logger for you. I think the way to configure a logger is through a configuration file (xml or property file). This however adds complexity to the implementation and for the user, so I think we should have a better reason to require it. The only optimization I can think of, is using a local cache (ie. `Map<String, Boolean>` which gets filled lazily)

**Comment by patrickfav** [comment]
Closing since PR is merged.
